#!/bin/bash
#$ -l mem_free=1G
#$ -l h_vmem=1G
#$ -l h_rt=24:00:00
#$ -cwd
#$ -j y
#$ -R y
#$ -t 1-3

mkdir -p truth
output_file="truth/run-$SGE_TASK_ID.rds"
if [ ! -f $output_file ]; then
	Rscript getTruthParal.R $SGE_TASK_ID
fi;


